import React, { useState } from 'react';
import { FinancialState, SyncSettings } from '../types';
import { connectCloudAccount } from '../services/googleDriveService';

interface BackupPageProps {
  state: FinancialState;
  setState: React.Dispatch<React.SetStateAction<FinancialState>>;
  onSyncNow: () => void;
  isSyncing: boolean;
  onUpdateSyncSettings: (settings: Partial<SyncSettings>) => void;
}

const BackupPage: React.FC<BackupPageProps> = ({ state, setState, onSyncNow, isSyncing, onUpdateSyncSettings }) => {
  const [connecting, setConnecting] = useState(false);
  const [tempClientId, setTempClientId] = useState(state.syncSettings.googleClientId || '');

  const handleCloudConnect = async () => {
    if (tempClientId.trim().length === 0) {
      alert("Please enter a valid Google Cloud Client ID to proceed.");
      return;
    }

    // Save ID if it changed
    if (tempClientId !== state.syncSettings.googleClientId) {
      onUpdateSyncSettings({ googleClientId: tempClientId.trim() });
    }

    setConnecting(true);
    try {
      await connectCloudAccount(tempClientId.trim());
      onUpdateSyncSettings({ 
        isConnected: true, 
        cloudUser: { 
          name: state.currentUser?.name || "Authorized User", 
          email: state.currentUser?.email || "ieee_sync@google.com" 
        } 
      });
    } catch (err) {
      console.error("Cloud Connection Failed", err);
      alert("Connection failed. Please check your internet or Client ID permissions.");
    } finally {
      setConnecting(false);
    }
  };

  const handleExport = () => {
    const dataStr = JSON.stringify(state);
    const blob = new Blob([dataStr], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `ieee_backup_${new Date().toISOString().split('T')[0]}.json`;
    link.click();
  };

  const handleImport = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const json = e.target?.result as string;
        const parsedState = JSON.parse(json);
        
        // Basic validation
        if (!parsedState.societies || !Array.isArray(parsedState.societies)) {
           throw new Error("Invalid backup format: Missing societies data");
        }

        if (window.confirm("WARNING: Restoring this backup will overwrite all current application data (Transactions, Events, Budgets). This action cannot be undone.\n\nAre you sure you want to proceed?")) {
            setState(prev => ({
                ...parsedState,
                // Critical: Preserve the current session user to prevent lockout/inconsistency
                currentUser: prev.currentUser,
                // Preserve sync settings client ID if missing in backup to avoid disconnection
                syncSettings: {
                    ...parsedState.syncSettings,
                    googleClientId: parsedState.syncSettings?.googleClientId || prev.syncSettings.googleClientId
                }
            }));
            alert("Backup restored successfully! The dashboard has been updated.");
        }
      } catch (err) {
        console.error("Import failed", err);
        alert("Failed to import backup. Please ensure the file is a valid JSON backup generated by this application.");
      }
    };
    reader.readAsText(file);
    // Reset input value to allow same file selection again if needed
    event.target.value = '';
  };

  return (
    <div className="max-w-3xl mx-auto space-y-6 pb-20">
      <div className="text-center py-8">
        <h2 className="text-3xl font-black text-slate-900 tracking-tight">Data Management</h2>
        <p className="text-slate-500 mt-2 font-medium">Cloud synchronization and local backup controls.</p>
      </div>

      {/* Cloud Sync Section */}
      <div className="bg-white rounded-3xl shadow-xl shadow-slate-200 overflow-hidden border border-slate-100">
         <div className="h-1.5 bg-gradient-to-r from-blue-500 via-red-500 to-yellow-500"></div>
         
         <div className="p-8 md:p-12">
            {!state.syncSettings.isConnected ? (
                // Disconnected / Login State
                <div className="flex flex-col items-center text-center space-y-8">
                    <div className="w-20 h-20 bg-slate-50 rounded-full flex items-center justify-center border border-slate-100 shadow-inner">
                        <i className="fa-brands fa-google-drive text-4xl text-slate-700"></i>
                    </div>
                    
                    <div className="max-w-md w-full space-y-5">
                       <div>
                          <label className="block text-xs font-bold text-slate-400 uppercase mb-2 text-left tracking-wider">Configuration: Client ID</label>
                          <input 
                             type="text" 
                             value={tempClientId}
                             onChange={(e) => setTempClientId(e.target.value)}
                             placeholder="Enter Google Cloud Client ID"
                             className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl text-sm font-medium outline-none focus:ring-2 focus:ring-blue-500 transition-all placeholder:text-slate-300"
                          />
                          {!state.syncSettings.googleClientId && (
                              <p className="text-[10px] text-slate-400 mt-1.5 text-left flex items-center">
                                <i className="fa-solid fa-circle-info mr-1"></i>
                                Required for first-time authentication.
                              </p>
                          )}
                       </div>

                       <button 
                         onClick={handleCloudConnect}
                         disabled={connecting}
                         className="w-full py-4 bg-slate-900 text-white rounded-xl font-bold text-lg hover:bg-slate-800 transition-all active:scale-95 flex items-center justify-center space-x-3 shadow-lg shadow-slate-200 disabled:opacity-70 disabled:cursor-not-allowed"
                       >
                          {connecting ? (
                            <i className="fa-solid fa-circle-notch fa-spin"></i>
                          ) : (
                            <i className="fa-brands fa-google"></i>
                          )}
                          <span>{connecting ? 'Connecting...' : 'Sign in with Google'}</span>
                       </button>
                    </div>
                </div>
            ) : (
                // Connected / Sync State
                <div className="space-y-8">
                    <div className="flex items-center space-x-4 bg-green-50 p-5 rounded-2xl border border-green-100">
                        <div className="w-12 h-12 bg-white rounded-full flex items-center justify-center text-green-600 shrink-0 shadow-sm">
                            <i className="fa-solid fa-user-check text-xl"></i>
                        </div>
                        <div className="flex-1 min-w-0">
                            <h3 className="font-bold text-slate-900">Account Connected</h3>
                            <p className="text-sm text-slate-600 truncate">{state.syncSettings.cloudUser?.email}</p>
                        </div>
                        <button 
                          onClick={() => onUpdateSyncSettings({ isConnected: false })} 
                          className="text-xs font-bold text-red-500 hover:bg-white hover:shadow-sm px-4 py-2 rounded-xl transition-all"
                        >
                            Disconnect
                        </button>
                    </div>

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                        <button 
                            disabled={isSyncing}
                            onClick={onSyncNow}
                            className="group relative overflow-hidden py-6 bg-blue-600 text-white rounded-2xl font-bold text-lg hover:bg-blue-700 transition-all shadow-xl shadow-blue-100 flex flex-col items-center justify-center h-40 active:scale-95"
                        >
                             <div className="absolute top-0 right-0 p-3 opacity-10">
                                <i className="fa-solid fa-cloud text-6xl transform rotate-12"></i>
                             </div>
                             {isSyncing ? (
                                <i className="fa-solid fa-circle-notch fa-spin text-3xl mb-3"></i>
                             ) : (
                                <i className="fa-solid fa-cloud-arrow-up text-3xl mb-3 group-hover:-translate-y-1 transition-transform"></i>
                             )}
                             <span>{isSyncing ? 'Syncing...' : 'Sync Now'}</span>
                        </button>

                         <button 
                            onClick={() => onUpdateSyncSettings({ autoSync: !state.syncSettings.autoSync })}
                            className={`group relative overflow-hidden py-6 rounded-2xl font-bold text-lg border-2 transition-all flex flex-col items-center justify-center h-40 active:scale-95 ${
                              state.syncSettings.autoSync 
                                ? 'bg-emerald-50 border-emerald-500 text-emerald-700' 
                                : 'bg-white border-slate-200 text-slate-400 hover:border-slate-300 hover:bg-slate-50'
                            }`}
                        >
                             <div className="absolute top-0 right-0 p-3 opacity-10">
                                <i className="fa-solid fa-rotate text-6xl transform -rotate-12"></i>
                             </div>
                             <i className={`fa-solid ${state.syncSettings.autoSync ? 'fa-toggle-on text-emerald-600' : 'fa-toggle-off'} text-3xl mb-3 transition-colors`}></i>
                             <span>Auto-Sync: {state.syncSettings.autoSync ? 'ON' : 'OFF'}</span>
                        </button>
                    </div>

                    <div className="text-center pt-2">
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Last Synced Timestamp</p>
                        <p className="text-sm font-bold text-slate-700 font-mono">
                            {state.syncSettings.lastSyncedAt ? new Date(state.syncSettings.lastSyncedAt).toLocaleString() : '--'}
                        </p>
                    </div>
                </div>
            )}
         </div>
      </div>
      
      {/* Local Backup Section */}
      <div className="mt-8 pt-6 border-t border-slate-200">
        <h3 className="text-lg font-bold text-slate-800 mb-4 text-center">Local Backup Controls</h3>
        <div className="bg-slate-50 rounded-2xl p-6 flex flex-col sm:flex-row items-center justify-center gap-4 border border-slate-100">
           <button 
              onClick={handleExport} 
              className="w-full sm:w-auto group inline-flex items-center justify-center space-x-2 px-6 py-3 rounded-xl bg-white border border-slate-200 text-slate-600 text-sm font-bold hover:bg-slate-50 hover:border-slate-300 hover:text-slate-900 transition-all shadow-sm hover:shadow-md"
           >
              <i className="fa-solid fa-download text-blue-500 group-hover:scale-110 transition-transform"></i>
              <span>Export JSON</span>
           </button>
           
           <div className="relative w-full sm:w-auto">
             <input
               type="file"
               accept=".json"
               onChange={handleImport}
               className="hidden"
               id="import-backup-input"
             />
             <label 
                htmlFor="import-backup-input"
                className="w-full sm:w-auto group inline-flex items-center justify-center space-x-2 px-6 py-3 rounded-xl bg-white border border-slate-200 text-slate-600 text-sm font-bold hover:bg-slate-50 hover:border-slate-300 hover:text-slate-900 transition-all shadow-sm hover:shadow-md cursor-pointer"
             >
                <i className="fa-solid fa-file-import text-green-500 group-hover:scale-110 transition-transform"></i>
                <span>Import JSON</span>
             </label>
           </div>
        </div>
        <p className="text-[10px] text-slate-400 text-center mt-3 max-w-md mx-auto">
          Importing a file will completely replace your current dashboard data. We recommend exporting your current data before performing an import.
        </p>
      </div>
    </div>
  );
};

export default BackupPage;